### ISSUE TITLE
modestga zero division error

### ISSUE THREAD

**Issue by krzysztofarendt** [sdu-cfei/modest-py#64]
When running the example `simple_1param.py` we get a zero division error from `modestga`:
```
(venv) (base) D:\code\modest-py>python examples\simple\simple_1param.py
Traceback (most recent call last):
  File "examples\simple\simple_1param.py", line 70, in <module>
    estimates = session.estimate()
  File "d:\code\modest-py\modestpy\estimation.py", line 299, in estimate
    m_estimates = m_inst.estimate()
  File "d:\code\modest-py\modestpy\estim\ga_parallel\ga_parallel.py", line 309, in estimate
    out = minimize(
  File "D:\code\modest-py\venv\lib\site-packages\modestga\ga.py", line 199, in minimize
    mut_rate /= 1 - 1 / len(bounds)                 # Mutate more often
ZeroDivisionError: float division by zero
```

It happens when running `modestga` with default parameters.

**Comment by filokot** [comment]
An observation:

The error comes from the estimation method parameter **est** in the simple_1param.py:
![image](https://user-images.githubusercontent.com/38052193/95911745-26197e00-0da2-11eb-8b68-1a51fb2d62f0.png)

Since **est** represents a single unknown (C) and therefore contains a single-key dict with a 1D list value <=est.json. Correspondingly, the variable **b** (=list of tuples of length **est**) of the MODESTGA object (ga_parallel.py, line 305) becomes a list of single tuple element and is passed as parameter **bounds** to the method minimize defined in ga.py 

![image](https://user-images.githubusercontent.com/38052193/95915626-b4443300-0da7-11eb-84c1-1c3a718fce28.png)

Therefore, len(bounds) => (len(bounds) = 1) => 1-1/len(bounds) => division by zero in line 199 of ga.py

![image](https://user-images.githubusercontent.com/38052193/95915728-e35aa480-0da7-11eb-8c94-f57120b7ea9a.png)


Keeping two variables unknown (C and R1) instead of one in simple_1param.py leads to the list of bounds containing two elements => 1 - 1/len(bounds) = 1 - 1/2 = 0.5 which "fixes" the problem:
![image](https://user-images.githubusercontent.com/38052193/95912587-4990f880-0da3-11eb-95f7-5fb74381711c.png)
![image](https://user-images.githubusercontent.com/38052193/95914610-477c6900-0da6-11eb-946c-4efb0ebea581.png)


Therefore, to enable estimation of a single unknown parameter in ModestPy, it seems appropriate to replace len(bounds) by len(bounds)+0.01 in the denominator or something else of this sort.

**Comment by krzysztofarendt** [comment]
Thanks for tracking down the error. I fixed it in `modestga`: https://github.com/krzysztofarendt/modestga/commit/24f69e63bd4cf57da23ab4a92caabf7f2357d0a9

You need to update the package: `pip install -U modestga`
